#ifndef DEF_CST_CHARACTER_SPRITE
#define DEF_CST_CHARACTER_SPRITE

#define CHARACTER_SPRITE_CORAN_EYES_X 13
#define CHARACTER_SPRITE_CORAN_EYES_Y 10
#define CHARACTER_SPRITE_CORAN_BUTT_Y 33
#define CHARACTER_SPRITE_HUMAN_EYES_X 13
#define CHARACTER_SPRITE_HUMAN_EYES_Y 10
#define CHARACTER_SPRITE_HUMAN_BUTT_Y 33
#define CHARACTER_SPRITE_DWARF_EYES_X 13
#define CHARACTER_SPRITE_DWARF_EYES_Y 13
#define CHARACTER_SPRITE_DWARF_BUTT_Y 33
#define CHARACTER_SPRITE_ELF_EYES_X 13
#define CHARACTER_SPRITE_ELF_EYES_Y 10
#define CHARACTER_SPRITE_ELF_BUTT_Y 33
#define CHARACTER_SPRITE_SANAK_EYES_X 13
#define CHARACTER_SPRITE_SANAK_EYES_Y 10
#define CHARACTER_SPRITE_SANAK_BUTT_Y 33
#define CHARACTER_SPRITE_FAIRY_EYES_X 13
#define CHARACTER_SPRITE_FAIRY_EYES_Y 10
#define CHARACTER_SPRITE_FAIRY_BUTT_Y 33
#define CHARACTER_SPRITE_EYES_WIDTH 14
#define CHARACTER_SPRITE_EYES_HEIGHT 8
#define CHARACTER_SPRITE_SIZE_WIDTH 40
#define CHARACTER_SPRITE_SIZE_HEIGHT 40
#define CHARACTER_SPRITE_MARGIN_TOP 4
#define CHARACTER_SPRITE_MARGIN_BOTTOM 0
#define CHARACTER_SPRITE_MARGIN_LEFT 9
#define CHARACTER_SPRITE_MARGIN_RIGHT 9
#define CHARACTER_SPRITE_PATH "resource/images/sprites/characters/"
#define CHARACTER_SPRITE_FLAGS SDL_HWSURFACE

#endif