#ifndef DEF_CST_CHARACTER_HITBOX
#define DEF_CST_CHARACTER_HITBOX

#define CHARACTER_HITBOX_Y 10
#define CHARACTER_HITBOX_X -10
#define CHARACTER_HITBOX_W 19
#define CHARACTER_HITBOX_H 15
#define CHARACTER_HITBOX_CHECK_WIDTH 50
#define CHARACTER_HITBOX_CHECK_HEIGHT 50

#endif