#ifndef DEF_CST_CONTROLS
#define DEF_CST_CONTROLS

#define CONTROLS_MOVEMENT_UP SDLK_w
#define CONTROLS_MOVEMENT_DOWN SDLK_s
#define CONTROLS_MOVEMENT_LEFT SDLK_a
#define CONTROLS_MOVEMENT_RIGHT SDLK_d
#define CONTROLS_MOVEMENT_RUN SDLK_l
#define CONTROLS_ACTION SDLK_RETURN
#define CONTROLS_PAUSE SDLK_ESCAPE
#define CONTROLS_CLOSE SDLK_BACKSPACE
#define CONTROLS_SWITCH SDLK_TAB

#endif