#ifndef DEF_CST_ENGINE
#define DEF_CST_ENGINE

#define ENGINE_INIT_IMG_FLAGS IMG_INIT_PNG
#define ENGINE_INIT_SDL_FLAGS SDL_INIT_VIDEO
#define ENGINE_INIT_MIX_FLAGS MIX_INIT_FLAC
#define ENGINE_MIXER_FREQUENCY 22050
#define ENGINE_MIXER_FORMAT MIX_DEFAULT_FORMAT
#define ENGINE_MIXER_CHANNELS MIX_DEFAULT_CHANNELS
#define ENGINE_MIXER_CHUNKSIZE 2048

#endif