#ifndef DEF_CST_ITEM
#define DEF_CST_ITEM

#define ITEM_ARMOR_BAG_MAX_SIZE 15
#define ITEM_ITEM_BAG_MAX_SIZE 10
#define ITEM_POTION_DEFAULT_WEIGHT 1
#define ITEM_POTION_FLAGS SDL_HWSURFACE | SDL_SRCALPHA
#define ITEM_POTION_PATH "resource/items/potions/"
#define ITEM_BOOK_DEFAULT_WEIGHT 1
#define ITEM_BOOK_FLAGS SDL_HWSURFACE | SDL_SRCALPHA
#define ITEM_BOOK_PATH "resource/items/books/"
#define ITEM_ARMOR_FLAGS SDL_HWSURFACE | SDL_SRCALPHA
#define ITEM_ARMOR_PATH "resource/items/armors/"
#define ITEM_WEAPON_FLAGS SDL_HWSURFACE | SDL_SRCALPHA
#define ITEM_WEAPON_PATH "resource/items/weapons/"
#define ITEM_MISC_FLAGS SDL_HWSURFACE | SDL_SRCALPHA
#define ITEM_MISC_PATH "resource/items/miscs/"

#endif