#ifndef DEF_CST_MENU
#define DEF_CST_MENU

#define MENU_SCROLLBAR_ITEM_EXCHANGE_WIDTH 15
#define MENU_TABS_PREVIEW_ITEM_EXCHANGE_HEIGHT 20
#define MENU_TABS_PREVIEW_SEPARATION_WIDTH 1
#define MENU_TABS_PREVIEW_ICON_HEIGHT 12
#define MENU_TABS_PREVIEW_ICON_WIDTH 12
#define MENU_TABS_PREVIEW_ICON_PATH "resource/images/menu/tab_previews/tab_preview_"
#define MENU_TABS_PREVIEW_SELECTION_WIDTH 2
#define MENU_TAB_CONTENT_DEFAULT_ENTRY_HEIGHT 30
#define MENU_TAB_CONTENT_ITEM_EXCHANGE_ENTRY_HEIGHT 25
#define MENU_TAB_CONTENT_ITEM_EXCHANGE_ENTRY_PADDING 1
#define MENU_TAB_CONTENT_SELECTION_WIDTH 10
#define MENU_HEADER_ITEM_EXCHANGE_HEIGHT 50
#define MENU_HEADER_MARGIN 5
#define MENU_ITEM_PREVIEW_BORDERS_WIDTH 6
#define MENU_ITEM_PREVIEW_BORDERS_RADIUS 10
#define MENU_ITEM_PREVIEW_WIDTH 140
#define MENU_ITEM_PREVIEW_HEIGHT 100
#define MENU_ITEM_PREVIEW_MARGIN 30
#define MENU_DEFAULT_PADDING 2
#define MENU_COLORS_DEPTH 32
#define MENU_COLORS_BORDERS_R 52
#define MENU_COLORS_BORDERS_G 172
#define MENU_COLORS_BORDERS_B 35
#define MENU_COLORS_BACKGROUND_R 10
#define MENU_COLORS_BACKGROUND_G 10
#define MENU_COLORS_BACKGROUND_B 10
#define MENU_COLORS_FONT_R 200
#define MENU_COLORS_FONT_G 200
#define MENU_COLORS_FONT_B 200
#define MENU_COLORS_SELECTION_R 35
#define MENU_COLORS_SELECTION_G 182
#define MENU_COLORS_SELECTION_B 163
#define MENU_BORDERS_WIDTH 6
#define MENU_BORDERS_RADIUS 10
#define MENU_CONTAINER_SEPARATION_WIDTH 1
#define MENU_FLAGS SDL_HWSURFACE | SDL_SRCALPHA

#endif