#ifndef DEF_CST_STRUCT_SPRITE
#define DEF_CST_STRUCT_SPRITE

#define STRUCT_SPRITE_PATH "resource/images/sprites/textures/buildings/"
#define STRUCT_SPRITE_COLORS_DEPTH 32
#define STRUCT_SPRITE_GRID_HEIGHT 40
#define STRUCT_SPRITE_GRID_WIDTH 40
#define STRUCT_SPRITE_FLAGS SDL_HWSURFACE | SDL_DOUBLEBUF

#endif