#ifndef CST_ITEM_CATEGORIES
#define CST_ITEM_CATEGORIES

#define ITEM_CATEGORY_POTION 0x1
#define ITEM_CATEGORY_ARMOR 0x2
#define ITEM_CATEGORY_WEAPON 0x3
#define ITEM_CATEGORY_BOOK 0x4
#define ITEM_CATEGORY_MISC 0x5

#endif
