CC=gcc
CC_FLAGS=-g\
				 -Wall\
				 -Wextra\
				 -Werror\
				 -c\

all:
	$(MAKE) -C main_menu all
	$(MAKE) -C character_creation all

clean:
	$(MAKE) -C main_menu clean
	$(MAKE) -C character_creation clean

re:
	$(MAKE) -C main_menu re
	$(MAKE) -C character_creation re
